spring:
  application:
    name: config-service
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaoziqiangshicaicai/Zn-config
          search-paths: config
server:
  port: 6001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka